# Generated by Django 5.2.9 on 2026-01-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignanalytics",
            options={"verbose_name_plural": "Campaign Analytics"},
        ),
        migrations.AlterModelOptions(
            name="useranalytics",
            options={"verbose_name_plural": "User Analytics"},
        ),
    ]
