# Generated by Django 5.2.9 on 2026-01-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("timeout", models.PositiveIntegerField(default=60)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("backoff", models.PositiveIntegerField(default=5)),
                ("priority", models.PositiveSmallIntegerField(default=10)),
                ("pending_jobs", models.PositiveIntegerField(default=0)),
                ("failed_jobs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
