# Generated by Django 5.2.9 on 2026-01-14 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("smtp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("body_plain", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("retried", "Retried"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("retries", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "sender_smtp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="smtp.smtpaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageOpen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beacon_uuid", models.CharField(max_length=36)),
                ("ip_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent_family", models.CharField(blank=True, max_length=50)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opens",
                        to="message_system.message",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["beacon_uuid"], name="message_sys_beacon__f714aa_idx"
                    ),
                    models.Index(
                        fields=["opened_at"], name="message_sys_opened__77ca31_idx"
                    ),
                ],
            },
        ),
    ]
