# Generated by Django 5.2.9 on 2026-01-14 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("subscribed", "Subscribed"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complaint", "Complaint"),
                            ("pending", "Pending"),
                        ],
                        default="subscribed",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("import_source", models.CharField(blank=True, max_length=100)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("filter_criteria", models.JSONField(blank=True, default=dict)),
                ("is_dynamic", models.BooleanField(default=False)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("complaint", "Complaint"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_recipients",
                        to="message_system.contact",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="message_system.message",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="messageopen",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opens",
                to="message_system.messagerecipient",
            ),
        ),
        migrations.AddIndex(
            model_name="messageopen",
            index=models.Index(
                fields=["message", "recipient"], name="message_sys_message_acc661_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "status"], name="message_sys_user_id_d9f142_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "is_active"], name="message_sys_user_id_51ffe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="message_sys_email_9c8efc_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["created_at"], name="message_sys_created_e2d02e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user", "email"), name="unique_email_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactgroup",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_group_name_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["message", "status"], name="message_sys_message_d501d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["contact", "status"], name="message_sys_contact_03b173_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(fields=["status"], name="message_sys_status_a89821_idx"),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["sent_at"], name="message_sys_sent_at_614235_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "contact")},
        ),
    ]
