# Generated by Django 5.2.9 on 2026-01-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_system", "0002_contact_contactgroup_messagerecipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="message_system.contactgroup"
            ),
        ),
    ]
