# Generated by Django 5.2.9 on 2026-01-14 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("smtp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("failed_campaign", "Failed Campaign"),
                            ("smtp_unreachable", "SMTP Unreachable"),
                            ("threshold_exceeded", "Threshold Exceeded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "smtp_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="smtp.smtpaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="monitoring__user_id_ed84f7_idx"
                    ),
                    models.Index(
                        fields=["campaign"], name="monitoring__campaig_699381_idx"
                    ),
                    models.Index(
                        fields=["smtp_account"], name="monitoring__smtp_ac_7c3522_idx"
                    ),
                    models.Index(
                        fields=["alert_type"], name="monitoring__alert_t_b20e11_idx"
                    ),
                    models.Index(
                        fields=["is_resolved"], name="monitoring__is_reso_a46808_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="monitoring__created_5d4886_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "smtp_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics",
                        to="smtp.smtpaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="monitoring__user_id_8cfbb4_idx"
                    ),
                    models.Index(
                        fields=["campaign"], name="monitoring__campaig_1b1b80_idx"
                    ),
                    models.Index(
                        fields=["smtp_account"], name="monitoring__smtp_ac_d3e139_idx"
                    ),
                    models.Index(fields=["name"], name="monitoring__name_2c6ccf_idx"),
                    models.Index(
                        fields=["recorded_at"], name="monitoring__recorde_63c3d6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "smtp_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="smtp.smtpaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="monitoring__user_id_8c74ed_idx"
                    ),
                    models.Index(
                        fields=["campaign"], name="monitoring__campaig_1f1661_idx"
                    ),
                    models.Index(
                        fields=["smtp_account"], name="monitoring__smtp_ac_87b5d1_idx"
                    ),
                    models.Index(fields=["level"], name="monitoring__level_8fe2df_idx"),
                    models.Index(
                        fields=["created_at"], name="monitoring__created_e95237_idx"
                    ),
                ],
            },
        ),
    ]
