# Generated by Django 5.2.9 on 2026-01-14 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("message_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beacon_uuid", models.CharField(max_length=36)),
                ("url", models.URLField()),
                ("ip_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent_family", models.CharField(blank=True, max_length=50)),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="message_system.message",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["beacon_uuid"], name="tracking_cl_beacon__31cb3e_idx"
                    ),
                    models.Index(
                        fields=["clicked_at"], name="tracking_cl_clicked_9bf185_idx"
                    ),
                ],
            },
        ),
    ]
